# Generated by Django 6.0.1 on 2026-01-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_restaurant_picture_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='names',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
