# Generated by Django 6.0.1 on 2026-01-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_user_moblie_user_mobile_alter_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://b.zmtcdn.com/data/pictures/2/20565372/bccf6cabc04a24fa6c4ccfbb56ac6a99_featured_v2.jpg', max_length=1000)),
                ('cuisine', models.CharField(max_length=200)),
                ('Rating', models.FloatField()),
            ],
        ),
    ]
