# Generated by Django 6.0.1 on 2026-01-26 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.URLField(default='https://b.zmtcdn.com/data/pictures/2/20565372/bccf6cabc04a24fa6c4ccfbb56ac6a99_featured_v2.jpg', max_length=500),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('vegeterian', models.BooleanField(default=False)),
                ('picture', models.URLField(default='https://www.indiafilings.com/learn/wp-content/uploads/2024/08/How-to-Start-Food-Business.jpg', max_length=400)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.restaurant')),
            ],
        ),
    ]
